sudo: false
language: go
go:
  - 1.11.x
git:
  depth: 1

install: true
notifications:
  email: false

branches:
  only:
    - master

before_install:
  - go mod vendor

script:
  - go test -short -v -cover $(go list ./... | grep -v -e /vendor/)
